imports:
    - { resource: tables.yml }

services:
    phpbbgallery.featured.manager:
        class: phpbbgallery\featured\manager
        arguments:
            - '@dbal.conn'
            - '%phpbbgallery.featured.tables.featured%'
            - '%phpbbgallery.tables.gallery_images%'

    phpbbgallery.featured.controller:
        class: phpbbgallery\featured\controller\main
        arguments:
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@user'
            - '@phpbbgallery.core.auth'
            - '@phpbbgallery.core.image'
            - '@phpbbgallery.core.album'
            - '@phpbbgallery.featured.manager'

    phpbbgallery.featured.listener:
        class: phpbbgallery\featured\event\main_listener
        arguments:
            - '@controller.helper'
            - '@language'
            - '@template'
            - '@user'
            - '@phpbbgallery.core.auth'
            - '@phpbbgallery.core.config'
            - '@phpbbgallery.core.search'
            - '@phpbbgallery.featured.manager'
        tags:
            - { name: event.listener }
