parameters:
    phpbbgallery.core.file.source: '%core.root_path%files/phpbbgallery/core/source/'
    phpbbgallery.core.file.medium: '%core.root_path%files/phpbbgallery/core/medium/'
    phpbbgallery.core.file.mini: '%core.root_path%files/phpbbgallery/core/mini/'
    phpbbgallery.core.file.watermark: '%core.root_path%ext/phpbbgallery/core/images/watermark.png'

    phpbbgallery.tables.gallery_albums: '%core.table_prefix%gallery_albums'
    phpbbgallery.tables.gallery_contests: '%core.table_prefix%gallery_contests'
    phpbbgallery.tables.gallery_images: '%core.table_prefix%gallery_images'
    phpbbgallery.tables.gallery_moderators: '%core.table_prefix%gallery_modscache'
    phpbbgallery.tables.gallery_permissions: '%core.table_prefix%gallery_permissions'
    phpbbgallery.tables.gallery_roles: '%core.table_prefix%gallery_roles'
    phpbbgallery.tables.gallery_tracking: '%core.table_prefix%gallery_albums_track'
    phpbbgallery.tables.gallery_users: '%core.table_prefix%gallery_users'
    phpbbgallery.tables.gallery_comments: '%core.table_prefix%gallery_comments'
    phpbbgallery.tables.gallery_reports: '%core.table_prefix%gallery_reports'
    phpbbgallery.tables.gallery_rates: '%core.table_prefix%gallery_rates'
    phpbbgallery.tables.gallery_log: '%core.table_prefix%gallery_log'
    phpbbgallery.tables.gallery_watch: '%core.table_prefix%gallery_watch'
