parameters:
    phpbbgallery.core:
        file.source: '%core.root_path%files/phpbbgallery/core/source/'
        file.medium: '%core.root_path%files/phpbbgallery/core/medium/'
        file.mini: '%core.root_path%files/phpbbgallery/core/mini/'
        file.watermark: '%core.root_path%ext/phpbbgallery/core/images/watermark.png'

    phpbbgallery.tables:
        gallery_albums: '%core.table_prefix%gallery_albums'
        gallery_contests: '%core.table_prefix%gallery_contests'
        gallery_images: '%core.table_prefix%gallery_images'
        gallery_moderators: '%core.table_prefix%gallery_modscache'
        gallery_permissions: '%core.table_prefix%gallery_permissions'
        gallery_roles: '%core.table_prefix%gallery_roles'
        gallery_tracking: '%core.table_prefix%gallery_albums_track'
        gallery_users: '%core.table_prefix%gallery_users'
        gallery_comments: '%core.table_prefix%gallery_comments'
        gallery_reports: '%core.table_prefix%gallery_reports'
        gallery_rates: '%core.table_prefix%gallery_rates'
        gallery_log: '%core.table_prefix%gallery_log'
        gallery_watch: '%core.table_prefix%gallery_watch'
