parameters:
    phpbbgallery.core.file.source: '%core.root_path%files/phpbbgallery/core/source/'
    phpbbgallery.core.file.medium: '%core.root_path%files/phpbbgallery/core/medium/'
    phpbbgallery.core.file.mini: '%core.root_path%files/phpbbgallery/core/mini/'
    phpbbgallery.core.file.watermark: '%core.root_path%ext/phpbbgallery/core/images/watermark.png'

    phpbbgallery.tables.albums: '%core.table_prefix%gallery_albums'
    phpbbgallery.tables.contests: '%core.table_prefix%gallery_contests'
    phpbbgallery.tables.images: '%core.table_prefix%gallery_images'
    phpbbgallery.tables.moderators: '%core.table_prefix%gallery_modscache'
    phpbbgallery.tables.permissions: '%core.table_prefix%gallery_permissions'
    phpbbgallery.tables.roles: '%core.table_prefix%gallery_roles'
    phpbbgallery.tables.tracking: '%core.table_prefix%gallery_albums_track'
    phpbbgallery.tables.users: '%core.table_prefix%gallery_users'
    phpbbgallery.tables.comments: '%core.table_prefix%gallery_comments'
    phpbbgallery.tables.reports: '%core.table_prefix%gallery_reports'
    phpbbgallery.tables.rates: '%core.table_prefix%gallery_rates'
    phpbbgallery.tables.log: '%core.table_prefix%gallery_log'
    phpbbgallery.tables.watch: '%core.table_prefix%gallery_watch'
