language: php
dist: xenial

matrix:
    include:
        - php: 7.1
          env: DB=none;NOTESTS=1
        - php: 7.1
          env: DB=mariadb
        - php: 7.1
          env: DB=postgres
        - php: 7.1
          env: DB=sqlite3
        - php: 7.1
          env: DB=mysqli # MyISAM
        - php: 7.2
          env: DB=mysqli;COVER=1
        - php: 7.3
          env: DB=mysqli
        - php: 7.4.10
          env: DB=mysqli
        - php: nightly
          env: DB=mysqli
        - php: 7.1
          env: DB=mysqli;SLOW=1 # Functional tests
    allow_failures:
        - php: nightly
    fast_finish: true

env:
  global:
    - EXTNAME="phpbbgallery"  # CHANGE name of the extension HERE
    - EXTSNIFF="phpbbgallery/core"
    - GITREPO="phpbbgallery" # CHANGE name of the repository HERE
    - SNIFF="1"            # Should we run code sniffer on your code?
    - IMAGE_ICC="1"        # Should we run icc profile sniffer on your images?
    - EPV="1"              # Should we run EPV (Extension Pre Validator) on your code?
    - PHPBB_BRANCH="3.3.x"
    - COVERAGE="1"		   # Should we run coverage?

branches:
  only:
    - master
    - stable-3.2.1.0

services:
    - postgresql
    - mysql
    - memcached


install:
  - cd core
  - composer install --dev --no-interaction --prefer-source
  - cd ..
  - travis/prepare-phpbb.sh $EXTNAME $PHPBB_BRANCH
  - cd ../phpBB3
  - sh -c "if [ '$COVER' != '0' ]; then sed -i '/phpenv/d' travis/setup-php-extensions.sh; fi"
  - travis/prepare-extension.sh $EXTNAME $PHPBB_BRANCH
  - travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION
  - sh -c "if [ '$COVERAGE' != '0' ] && [ '$COVER' != '0' ]; then phpBB/ext/$EXTNAME/travis/prepare-covarage.sh $DB $TRAVIS_PHP_VERSION $EXTNAME; fi"
  - ../$EXTNAME/travis/prepare-epv.sh $EPV $NOTESTS

before_script:
  - travis/setup-database.sh $DB $TRAVIS_PHP_VERSION

script:
  - sh -c "if [ '$SNIFF' != '0' ]; then travis/ext-sniff.sh $DB $TRAVIS_PHP_VERSION $EXTSNIFF; fi"
  - sh -c "if [ '$IMAGE_ICC' != '0' ]; then travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION; fi"
  - sh -c "if [ '$DB' != 'none' ] && [ '$SLOW' != '1' ]; then phpBB/ext/$EXTNAME/travis/run-tests.sh $DB $TRAVIS_PHP_VERSION $EXTNAME; fi"
  - sh -c "if [ '$DB' != 'none' ] && [ '$SLOW' != '0' ]; then phpBB/ext/$EXTNAME/travis/run-slow-tests.sh $DB $TRAVIS_PHP_VERSION $EXTNAME $SLOW; fi"
  - sh -c "if [ '$EPV' != '0' -a '$NOTESTS' = '1' ]; then phpBB/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/core'; fi"
  - sh -c "if [ '$EPV' != '0' -a '$NOTESTS' = '1' ]; then phpBB/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/acpcleanup'; fi"
  - sh -c "if [ '$EPV' != '0' -a '$NOTESTS' = '1' ]; then phpBB/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/acpimport'; fi"
  - sh -c "if [ '$EPV' != '0' -a '$NOTESTS' = '1' ]; then phpBB/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/exif'; fi"

after_script:
  - sh -c "if [ '$COVERAGE' != '0' ]; then phpBB/ext/$EXTNAME/travis/send-coverage.sh $DB $TRAVIS_PHP_VERSION $GITREPO; fi"
