parameters:
    phpbbgallery.bbtagsbridge.tables.image_tags: '%core.table_prefix%gallery_image_tags'

services:
    phpbbgallery.bbtagsbridge.input_parser:
        class: phpbbgallery\bbtagsbridge\input_parser
        arguments:
            - '@config'
            - '@sitesplat.bbtags.manager'

    phpbbgallery.bbtagsbridge.album_scope_resolver:
        class: phpbbgallery\bbtagsbridge\album_scope_resolver
        arguments:
            - '@dbal.conn.driver'
            - '%phpbbgallery.tables.gallery_albums%'

    phpbbgallery.bbtagsbridge.image_tag_manager:
        class: phpbbgallery\bbtagsbridge\image_tag_manager
        arguments:
            - '@dbal.conn.driver'
            - '%phpbbgallery.bbtagsbridge.tables.image_tags%'
            - '%phpbbgallery.tables.gallery_images%'
            - '%sitesplat.bbtags.tables.bbtags%'
            - '%sitesplat.bbtags.tables.bbtags_context%'

    phpbbgallery.bbtagsbridge.image_search_query:
        class: phpbbgallery\bbtagsbridge\image_search_query

    phpbbgallery.bbtagsbridge.controller.tags:
        class: phpbbgallery\bbtagsbridge\controller\tag_controller
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@request'
            - '@user'
            - '@phpbbgallery.core.auth'
            - '@phpbbgallery.bbtagsbridge.album_scope_resolver'
            - '@sitesplat.bbtags.manager'

    phpbbgallery.bbtagsbridge.provider.gallery_images:
        class: phpbbgallery\bbtagsbridge\provider\image_provider
        arguments:
            - '@phpbbgallery.bbtagsbridge.image_tag_manager'
            - '@controller.helper'
        tags:
            - { name: sitesplat.bbtags.provider }

    phpbbgallery.bbtagsbridge.listener:
        class: phpbbgallery\bbtagsbridge\event\main_listener
        arguments:
            - '@auth'
            - '@request'
            - '@controller.helper'
            - '@template'
            - '@language'
            - '@user'
            - '@phpbbgallery.bbtagsbridge.image_tag_manager'
            - '@phpbbgallery.bbtagsbridge.input_parser'
            - '@phpbbgallery.bbtagsbridge.album_scope_resolver'
            - '@phpbbgallery.bbtagsbridge.image_search_query'
            - '@sitesplat.bbtags.manager'
            - '@sitesplat.bbtags.moderation'
            - '%phpbbgallery.bbtagsbridge.tables.image_tags%'
        tags:
            - { name: event.listener }
