services:
    phpbbgallery.exif.listener:
        class: phpbbgallery\exif\event\exif_listener
        arguments:
            - '@user'
            - '@phpbbgallery.core.config'
            - '@phpbbgallery.core.user'
            - '@phpbbgallery.core.storage.workspace'
        tags:
            - { name: event.listener }
