parameters:
    phpbbgallery.tables.gallery_albums: '%core.table_prefix%gallery_albums'
    phpbbgallery.tables.gallery_images: '%core.table_prefix%gallery_images'

services:
    phpbbgallery.acpcleanup.listener:
        class: phpbbgallery\acpcleanup\event\main_listener
        tags:
            - { name: event.listener }

    phpbbgallery.acpcleanup.cleanup:
        class: phpbbgallery\acpcleanup\cleanup
        arguments:
            - '@dbal.conn'
            - '@phpbbgallery.core.file.tool'
            - '@user'
            - '@language'
            - '@phpbbgallery.core.block'
            - '@phpbbgallery.core.album'
            - '@phpbbgallery.core.comment'
            - '@phpbbgallery.core.config'
            - '@phpbbgallery.core.log'
            - '@phpbbgallery.core.moderate'
            - '@phpbbgallery.core.user'
            - '%phpbbgallery.tables.gallery_albums%'
            - '%phpbbgallery.tables.gallery_images%'

    phpbbgallery.acpcleanup.bbcode.legacy_migrator:
        class: phpbbgallery\acpcleanup\bbcode\legacy_migrator
        arguments:
            - '@dbal.conn'
            - '@phpbbgallery.core.config'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.bbcodes%'
            - '%tables.posts%'
            - '%tables.privmsgs%'
            - '%tables.users%'
