parameters:
    phpbbgallery.acpcleanup.tables.albums: '%core.table_prefix%gallery_albums'
    phpbbgallery.acpcleanup.tables.images: '%core.table_prefix%gallery_images'

services:
    phpbbgallery.acpcleanup.cleanup:
        class: phpbbgallery\acpcleanup\cleanup
        arguments:
            - '@dbal.conn'
            - '@phpbbgallery.core.file.tool'
            - '@user'
            - '@language'
            - '@phpbbgallery.core.block'
            - '@phpbbgallery.core.album'
            - '@phpbbgallery.core.comment'
            - '@phpbbgallery.core.config'
            - '@phpbbgallery.core.log'
            - '@phpbbgallery.core.moderate'
            - '%phpbbgallery.acpcleanup.tables.albums%'
            - '%phpbbgallery.acpcleanup.tables.images%'