phpbbgallery_contest_search:
    path: /gallery/search/contests
    defaults: { _controller: phpbbgallery.contest.controller.winners:base, page: 1 }

phpbbgallery_contest_search_page:
    path: /gallery/search/contests/{page}
    defaults: { _controller: phpbbgallery.contest.controller.winners:base }
    requirements:
        page: \d+
